#!/bin/bash

# Script pour afficher toutes les URLs publiques de SAMA SYNDICAT

echo "🌐 URLS PUBLIQUES - SAMA SYNDICAT"
echo "================================="
echo ""

# Couleurs
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'

# Configuration
SERVER_URL="http://localhost:8070"
DATABASE="sama_syndicat_final_1756812346"

echo -e "${BLUE}🖥️ CONFIGURATION SERVEUR${NC}"
echo "========================"
echo -e "URL Serveur: ${GREEN}$SERVER_URL${NC}"
echo -e "Base de données: ${GREEN}$DATABASE${NC}"
echo -e "Port: ${GREEN}8070${NC}"
echo ""

echo -e "${YELLOW}📋 URLS D'ADMINISTRATION${NC}"
echo "========================"
echo -e "${CYAN}🔐 Connexion Admin:${NC}"
echo "   $SERVER_URL/web/login"
echo ""
echo -e "${CYAN}📊 Dashboard Principal:${NC}"
echo "   $SERVER_URL/web#action=&model=&view_type=&menu_id="
echo ""
echo -e "${CYAN}⚙️ Configuration Modules:${NC}"
echo "   $SERVER_URL/web#action=&model=ir.module.module&view_type=kanban&menu_id="
echo ""

echo -e "${YELLOW}🏢 URLS SAMA SYNDICAT - BACKEND${NC}"
echo "==============================="
echo -e "${CYAN}📊 Dashboard Syndicat:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.dashboard&view_type=kanban&menu_id="
echo ""
echo -e "${CYAN}👥 Gestion Adhérents:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.adherent&view_type=kanban&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.adherent&view_type=list&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.adherent&view_type=form&menu_id="
echo ""
echo -e "${CYAN}💰 Gestion Cotisations:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.cotisation&view_type=list&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.cotisation&view_type=form&menu_id="
echo ""
echo -e "${CYAN}🏛️ Assemblées Générales:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.assemblee&view_type=kanban&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.assemblee&view_type=calendar&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.assemblee&view_type=list&menu_id="
echo ""
echo -e "${CYAN}⚖️ Revendications:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.revendication&view_type=kanban&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.revendication&view_type=list&menu_id="
echo ""
echo -e "${CYAN}🎯 Actions Syndicales:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.action&view_type=kanban&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.action&view_type=list&menu_id="
echo ""
echo -e "${CYAN}🎓 Formations:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.formation&view_type=kanban&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.formation&view_type=list&menu_id="
echo ""
echo -e "${CYAN}🤝 Médiations:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.mediation&view_type=list&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.mediation&view_type=form&menu_id="
echo ""
echo -e "${CYAN}📢 Communications:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.communication&view_type=kanban&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.communication&view_type=list&menu_id="
echo ""
echo -e "${CYAN}📄 Conventions:${NC}"
echo "   $SERVER_URL/web#action=&model=syndicat.convention&view_type=list&menu_id="
echo "   $SERVER_URL/web#action=&model=syndicat.convention&view_type=form&menu_id="
echo ""

echo -e "${YELLOW}🌐 URLS PUBLIQUES - FRONTEND${NC}"
echo "============================"
echo -e "${PURPLE}Note: Les URLs publiques nécessitent la configuration du module Website d'Odoo${NC}"
echo ""
echo -e "${CYAN}🏠 Page d'Accueil Publique:${NC}"
echo "   $SERVER_URL/syndicat"
echo "   $SERVER_URL/syndicat/home"
echo ""
echo -e "${CYAN}ℹ️ À Propos du Syndicat:${NC}"
echo "   $SERVER_URL/syndicat/about"
echo "   $SERVER_URL/syndicat/presentation"
echo ""
echo -e "${CYAN}👥 Adhésion en Ligne:${NC}"
echo "   $SERVER_URL/syndicat/adhesion"
echo "   $SERVER_URL/syndicat/rejoindre"
echo ""
echo -e "${CYAN}📰 Actualités Publiques:${NC}"
echo "   $SERVER_URL/syndicat/actualites"
echo "   $SERVER_URL/syndicat/news"
echo ""
echo -e "${CYAN}📞 Contact:${NC}"
echo "   $SERVER_URL/syndicat/contact"
echo "   $SERVER_URL/syndicat/nous-contacter"
echo ""
echo -e "${CYAN}📋 Revendications Publiques:${NC}"
echo "   $SERVER_URL/syndicat/revendications"
echo "   $SERVER_URL/syndicat/nos-combats"
echo ""
echo -e "${CYAN}🎓 Formations Ouvertes:${NC}"
echo "   $SERVER_URL/syndicat/formations"
echo "   $SERVER_URL/syndicat/formation-inscription"
echo ""

echo -e "${YELLOW}🔧 URLS D'API ET SERVICES${NC}"
echo "========================="
echo -e "${CYAN}📊 API REST (si activée):${NC}"
echo "   $SERVER_URL/api/v1/syndicat/adherents"
echo "   $SERVER_URL/api/v1/syndicat/cotisations"
echo "   $SERVER_URL/api/v1/syndicat/assemblees"
echo ""
echo -e "${CYAN}📱 Services JSON-RPC:${NC}"
echo "   $SERVER_URL/jsonrpc"
echo ""
echo -e "${CYAN}🔐 Authentification OAuth:${NC}"
echo "   $SERVER_URL/oauth2/authorize"
echo "   $SERVER_URL/oauth2/token"
echo ""

echo -e "${YELLOW}📱 URLS MOBILES${NC}"
echo "==============="
echo -e "${CYAN}📱 Interface Mobile:${NC}"
echo "   $SERVER_URL/web/mobile"
echo ""
echo -e "${CYAN}📊 Dashboard Mobile:${NC}"
echo "   $SERVER_URL/web/mobile#action=&model=syndicat.dashboard"
echo ""

echo -e "${YELLOW}🛠️ URLS DE DÉVELOPPEMENT${NC}"
echo "========================="
echo -e "${CYAN}🔍 Mode Debug:${NC}"
echo "   $SERVER_URL/web?debug=1"
echo "   $SERVER_URL/web?debug=assets"
echo ""
echo -e "${CYAN}📊 Métriques et Monitoring:${NC}"
echo "   $SERVER_URL/web/database/manager"
echo "   $SERVER_URL/web/database/selector"
echo ""
echo -e "${CYAN}🔧 Configuration Technique:${NC}"
echo "   $SERVER_URL/web/webclient/version_info"
echo "   $SERVER_URL/web/session/get_session_info"
echo ""

echo -e "${YELLOW}📋 URLS SPÉCIFIQUES SAMA SYNDICAT${NC}"
echo "=================================="
echo -e "${CYAN}🎯 Actions Rapides:${NC}"
echo "   $SERVER_URL/web#action=syndicat_dashboard_action"
echo "   $SERVER_URL/web#action=syndicat_adherent_action"
echo "   $SERVER_URL/web#action=syndicat_cotisation_action"
echo ""
echo -e "${CYAN}📊 Rapports:${NC}"
echo "   $SERVER_URL/web#action=syndicat_rapport_adherents"
echo "   $SERVER_URL/web#action=syndicat_rapport_cotisations"
echo "   $SERVER_URL/web#action=syndicat_rapport_assemblees"
echo ""

echo -e "${YELLOW}🔗 LIENS DIRECTS UTILES${NC}"
echo "======================="
echo -e "${CYAN}🚀 Démarrage Rapide:${NC}"
echo "   $SERVER_URL/web/login?db=$DATABASE"
echo ""
echo -e "${CYAN}📊 Dashboard Direct:${NC}"
echo "   $SERVER_URL/web?db=$DATABASE#action=&model=syndicat.dashboard&view_type=kanban"
echo ""
echo -e "${CYAN}👥 Adhérents Direct:${NC}"
echo "   $SERVER_URL/web?db=$DATABASE#action=&model=syndicat.adherent&view_type=kanban"
echo ""

echo ""
echo -e "${GREEN}✅ VÉRIFICATION DE L'ÉTAT DU SERVEUR${NC}"
echo "===================================="

# Vérifier si le serveur est actif
if curl -s --connect-timeout 5 "$SERVER_URL" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Serveur ACTIF${NC} - Toutes les URLs sont accessibles"
else
    echo -e "${YELLOW}⚠️ Serveur INACTIF${NC} - Démarrer avec: ./start_sama_syndicat.sh"
fi

# Vérifier le port
if lsof -i:8070 >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Port 8070 OUVERT${NC}"
else
    echo -e "${YELLOW}⚠️ Port 8070 FERMÉ${NC}"
fi

echo ""
echo -e "${PURPLE}📝 NOTES IMPORTANTES:${NC}"
echo "====================="
echo "• Les URLs publiques nécessitent le module Website d'Odoo"
echo "• Certaines URLs peuvent nécessiter une authentification"
echo "• Les URLs d'API nécessitent une configuration spécifique"
echo "• Utilisez ?debug=1 pour le mode développement"
echo ""
echo -e "${GREEN}🎯 URL PRINCIPALE RECOMMANDÉE:${NC}"
echo -e "${CYAN}$SERVER_URL/web/login?db=$DATABASE${NC}"